//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DeliveryTarget.java
//  @ Date : 29/06/2012
//  @ Author : 
//
//



package cookItBO.schedule;

import java.util.ArrayList;

import cookItBO.common.Time;
import cookItBO.places.Location;


public class DeliveryTarget {
	private ArrayList<DeliveryOperation> deliveryOperation;
	private Location location;
	private final Time deliveryTime;
	
	public DeliveryTarget(Time t){
		deliveryTime=t;
		deliveryOperation=new ArrayList<DeliveryOperation>();
	}
	
	public void adddeliveryOperationInList(DeliveryOperation d){
		deliveryOperation.add(d);
	}

	public ArrayList<DeliveryOperation> getDeliveryOperation() {
		return deliveryOperation;
	}
	
	public Location getLocation() {
		return location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}
	public Time getDeliveryTime() {
		return deliveryTime;
	}
	
	
}
