//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DeliveryOperation.java
//  @ Date : 29/06/2012
//  @ Author : 
//
//



package cookItBO.schedule;

import cookItBO.common.Time;
import cookItBO.recipes.Product;


public class DeliveryOperation {
	private final int variation;
	private final Product product;
	
	public DeliveryOperation(Product p, int v){
		variation=v;
		product=p;
	}

	public int getVariation() {
		return variation;
	}

	public Product getProduct() {
		return product;
	}


}
