//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DeliverySchedule.java
//  @ Date : 29/06/2012
//  @ Author : 
//
//



package cookItBO.schedule;

import java.util.ArrayList;

import cookItBO.common.Date;
import cookItBO.common.Time;


public class DeliverySchedule {
	private final Date date;
	public final static Time CLIENT_DELIVERY_DURATION=new Time(0, 5, 0);
	public final static Time DEPOT_TRANSFER_DURATION=new Time(0, 5, 0);

	private ArrayList<Delivery> deliveryList;
	
	public DeliverySchedule(Date d){
		date=d;
		deliveryList=new ArrayList<Delivery>();
	}

	public void addDeliveryInList(Delivery d){
		deliveryList.add(d);
	}

	public Date getDate() {
		return date;
	}

	public ArrayList<Delivery> getDeliveryList() {
		return deliveryList;
	}
	

	
	
}
