//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Menu.java
//  @ Date : 29/06/2012
//  @ Author : 
//
//



package  cookItBO.recipes;

import java.util.ArrayList;

import cookItBO.common.Date;


public class Menu {
	private final Date date;
	private ArrayList<Product> productList;
	
	public Menu(Date date){
		this.date=date;
		productList=new ArrayList<Product>();
	}

	public void addProductInList(Product p){
		productList.add(p);
	}
	
	public Date getDate() {
		return date;
	}

	public ArrayList<Product> getProductList() {
		return productList;
	}
}
