//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Product.java
//  @ Date : 29/06/2012
//  @ Author : 
//
//



package  cookItBO.recipes;


public class Product {
	private final String name;
	
	private double weight;
	private double productionCost;
	private double sellingCost;
	
	public Product(String n){
		name=n;
	}
	
	public double getWeight() {
		return weight;
	}
	public void setWeight(double weight) {
		this.weight = weight;
	}
	public double getProductionCost() {
		return productionCost;
	}
	public void setProductionCost(double productionCost) {
		this.productionCost = productionCost;
	}
	public double getSellingCost() {
		return sellingCost;
	}
	public void setSellingCost(double sellingCost) {
		this.sellingCost = sellingCost;
	}
	public String getName() {
		return name;
	}
	
	
}
