//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Client.java
//  @ Date : 29/06/2012
//  @ Author : 
//
//



package  cookItBO.demand;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;

import cookItBO.actives.StockPlace;
import cookItBO.common.Place;
import cookItBO.places.GPSCoordinates;
import cookItBO.places.Location;


public class Client extends Location {
	public final Place placeType=Place.CLIENT;
	private String firstName;
	private String lastName;
	private String detail;
	private String creditCardInfo;
	private StockPlace closeStockPlace;

	private final int DISPLAY_SIZE=10;
	private final int TW_DISPLAY_SIZE=6;
	
	public Client(String fn,String ln){
		commandList=new ArrayList<Command>();
		firstName=fn;
		lastName=ln;
	}
	

	
	
	public ArrayList<Command> getCommandList() {
		return commandList;
	}

	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	public String getLastName() {
		return lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	public String getDetail() {
		return detail;
	}
	public void setDetail(String detail) {
		this.detail = detail;
	}
	public String getCreditCardInfo() {
		return creditCardInfo;
	}
	public void setCreditCardInfo(String creditCardInfo) {
		this.creditCardInfo = creditCardInfo;
	}

	public StockPlace getCloseStockPlace() {
		return closeStockPlace;
	}


	public void setCloseStockPlace(StockPlace closeStockPlace) {
		this.closeStockPlace = closeStockPlace;
	}




	public void paintItem(Graphics g, int displayTime) {
		int x=this.getXPositionOnFrame()-DISPLAY_SIZE/2;
		int y=this.getYPositionOnFrame()-DISPLAY_SIZE/2;
		g.setColor(Color.red);
		g.fillOval(x, y, DISPLAY_SIZE, DISPLAY_SIZE);
	}




	public void paintItemTW(Graphics g, int displayTime) {
		int x=this.getXPositionOnFrame()-DISPLAY_SIZE/2;
		int y=this.getYPositionOnFrame()-DISPLAY_SIZE/2;
		boolean ok=false;
		if(this.commandList!=null){
			for(Command c:this.commandList){
				ok|=c.acceptTime(displayTime);
			}
			if(ok){
				g.setColor(Color.green);
				x=this.getXPositionOnFrame()-TW_DISPLAY_SIZE/2;
				y=this.getYPositionOnFrame()-TW_DISPLAY_SIZE/2;
				g.fillOval(x, y, TW_DISPLAY_SIZE, TW_DISPLAY_SIZE);
			}
		}
	}
	
	
}
