//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Command.java
//  @ Date : 29/06/2012
//  @ Author : 
//
//



package  cookItBO.demand;

import java.util.ArrayList;

import cookItBO.common.Date;
import cookItBO.places.Location;
import cookItBO.recipes.Product;


public class Command {
	private final String commandId;
	private final Location location;
	private final Date date;
	private TimeWindow timeWindow;
	private ArrayList<Product> productList;
	
	public Command(String id, Location c, Date d){
		commandId=id;
		location=c;
		//update the chained commandList of the client
		c.addCommandInList(this);
		
		productList=new ArrayList<Product>();
		date=d;
	}
	
	public void addProductInList(Product p){
		productList.add(p);
	}
	
	public String getCommandId() {
		return commandId;
	}
	public Date getDate() {
		return date;
	}

	public TimeWindow getTimeWindow() {
		return timeWindow;
	}

	public void setTimeWindow(TimeWindow timeWindow) {
		this.timeWindow = timeWindow;
	}

	public ArrayList<Product> getProductList() {
		return productList;
	}

	public Location getLocation() {
		return location;
	}

	public boolean acceptTime(int displayTime) {
		// TODO Auto-generated method stub
		int min=this.timeWindow.getPreferedTime().toInt();
		int max=this.timeWindow.getPreferedTime().toInt()+this.timeWindow.getWindowWidth().toInt();
		return min<displayTime && max>displayTime;
	}

	
	
}
