//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TimeWindow.java
//  @ Date : 29/06/2012
//  @ Author : 
//
//



package  cookItBO.demand;

import cookItBO.common.Time;



public class TimeWindow {
	private Time preferedTime;
	private Time windowWidth;
	
	public TimeWindow(Time pt, Time ww){
		preferedTime=pt;
		windowWidth=ww;
	}
	
	public Time getPreferedTime() {
		return preferedTime;
	}
	public void setPreferedTime(Time preferedTime) {
		this.preferedTime = preferedTime;
	}
	public Time getWindowWidth() {
		return windowWidth;
	}
	public void setWindowWidth(Time windowWidth) {
		this.windowWidth = windowWidth;
	}
	
	
}
