//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GPSCoordinate.java
//  @ Date : 29/06/2012
//  @ Author : 
//
//



package  cookItBO.places;

import gui.GraphPanel;
import instanceGenerator.InstanceGenerator;


public class GPSCoordinates {
	public final double latitude;
	public final double longitude;
	public final double altitude;
	
	public GPSCoordinates(double lat,double lon,double alt){
		latitude=lat;
		longitude=lon;
		altitude=alt;
	}
	
	public double getLatitude() {
		return latitude;
	}
	public double getLongitude() {
		return longitude;
	}
	public double getAltitude() {
		return altitude;
	}
	
	public static double getDistance(GPSCoordinates p1,GPSCoordinates p2){
		return Math.sqrt((p1.latitude-p2.latitude) *(p1.latitude-p2.latitude) 
			+ (p1.longitude-p2.longitude)*(p1.longitude-p2.longitude)
			+ (p1.altitude-p2.altitude)*(p1.altitude-p2.altitude));
	}
	
	

}
