//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Location.java
//  @ Date : 29/06/2012
//  @ Author : 
//
//



package  cookItBO.places;

import gui.GraphPanel;
import instanceGenerator.InstanceGenerator;

import java.awt.Graphics;
import java.util.ArrayList;

import cookItBO.common.Place;
import cookItBO.demand.Command;


public abstract class Location {
	public final Place placeType=Place.UNDEFINED;
	protected int number;
	protected String suffix;
	protected String street;
	protected String city;
	protected int postalCode;
	protected GPSCoordinates coordinates;
	/**
	 * Chained list, refreshed when a command concerning this Location is created.
	 */
	protected ArrayList<Command> commandList;
	

	public void addCommandInList(Command c){
		commandList.add(c);
	}
	
	public int getNumber() {
		return number;
	}
	public void setNumber(int number) {
		this.number = number;
	}
	public String getSuffix() {
		return suffix;
	}
	public void setSuffix(String suffix) {
		this.suffix = suffix;
	}
	public String getStreet() {
		return street;
	}
	public void setStreet(String street) {
		this.street = street;
	}
	public String getCity() {
		return city;
	}
	public void setCity(String city) {
		this.city = city;
	}
	public int getPostalCode() {
		return postalCode;
	}
	public void setPostalCode(int postalCode) {
		this.postalCode = postalCode;
	}
	public GPSCoordinates getCoordinates() {
		return coordinates;
	}
	public void setCoordinates(GPSCoordinates coordinates) {
		this.coordinates = coordinates;
	}
	
	public String getAdress(){
		return (this.number+" "+this.suffix+" "+this.street+" "+this.city);
	}
	
	public int getXPositionOnFrame(){
		 double ratio= (double)(GraphPanel.WIDTH)/(InstanceGenerator.maxXCoord-InstanceGenerator.minXCoord);
		 return (int)((coordinates.latitude-InstanceGenerator.minXCoord)*ratio);
		}
	public int getYPositionOnFrame(){
		 double ratio= (double)(GraphPanel.HEIGHT)/(InstanceGenerator.maxYCoord-InstanceGenerator.minYCoord);
		 return (int)((coordinates.longitude-InstanceGenerator.minYCoord)*ratio);
	}
	

}
