//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : HQ.java
//  @ Date : 29/06/2012
//  @ Author : 
//
//



package cookItBO.actives;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;

import cookItBO.common.Place;
import cookItBO.common.Vehicle;
import cookItBO.demand.Command;
import cookItBO.places.Location;
import cookItBO.recipes.Product;

public class HQ extends StockPlace {
	private final Place placeTime=Place.HQ;
	private ArrayList<Vehicle> vehicleList;
	private final int DISPLAY_SIZE=20;
	public HQ(){
		commandList=null;
		vehicleList=new ArrayList<Vehicle>();
		productList=new ArrayList<Product>();
	}
	
	public void addVehicleInList(Vehicle v){
		vehicleList.add(v);
	}
	
	public ArrayList<Vehicle> getVehicleList() {
		return vehicleList;
	}

	public void paintItem(Graphics g) {
		int x=this.getXPositionOnFrame()-DISPLAY_SIZE/2;
		int y=this.getYPositionOnFrame()-DISPLAY_SIZE/2;
		g.setColor(Color.pink);
		g.fillOval(x, y, DISPLAY_SIZE, DISPLAY_SIZE);
	}
	
	
}
