//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StockPlace.java
//  @ Date : 29/06/2012
//  @ Author : 
//
//



package cookItBO.actives;

import java.util.ArrayList;

import cookItBO.places.Location;
import cookItBO.recipes.Product;
import cookItBO.schedule.DeliveryTarget;


public abstract class StockPlace extends Location {
	protected ArrayList<Product> productList;
	
	public void addProductInList(Product p){
		productList.add(p);
	}
	

	public ArrayList<Product> getProductList() {
		return productList;
	}
	
}
